version: 0.2

phases:
  pre_build:
    commands:
      - echo Logando no Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Buildando a imagem Docker...
      - docker build -t tool-go-tracking .
      - docker tag toolgo-tracker:latest 123456789012.dkr.ecr.us-east-1.amazonaws.com/toolgo-tracker:latest
  post_build:
    commands:
      - echo Enviando imagem para o ECR...
      - docker push 123456789012.dkr.ecr.us-east-1.amazonaws.com/toolgo-tracker:latest
      - echo Criando arquivo imagedefinitions.json...
      - |
        echo '[{
          "name": "toolgo-tracker",
          "imageUri": "123456789012.dkr.ecr.us-east-1.amazonaws.com/toolgo-tracker:latest"
        }]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
